In [1]:
import numpy as np

In [23]:
# Задание 1
N = int(input())
a = np.arange(0,N)
a = a[::-1]
a

20


array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [26]:
# Задание 2
N = int(input())
a = np.diag(np.arange(N)[::-1],k=0)
a

10


array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [30]:
a.trace()

45

In [40]:
# Задание 5
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])

from numpy import linalg

linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [34]:
np.allclose(np.dot(a, linalg.solve(a,b)),b)

True